[workspace]
resolver = "2"
members = ["tauri", "boa_utils", "nyanpasu-macro", "nyanpasu-egui"]

[workspace.package]
repository = "https://github.com/keiko233/clash-nyanpasu.git"
edition = "2021"
license = "GPL-3.0"
authors = ["zzzgydi", "keiko233"]

[workspace.dependencies]
thiserror = "2"
tracing = "0.1"
boa_engine = { version = "0.20" }

[profile.release]
panic = "unwind"
codegen-units = 1
lto = true
opt-level = "s"
