name: '[Single] Send Message to Telegram'

on:
  workflow_dispatch:
    inputs:
      nightly:
        description: 'Nightly'
        required: true
        type: boolean
        default: false

  workflow_call:
    inputs:
      nightly:
        description: 'Nightly'
        required: true
        type: boolean
        default: false

jobs:
  telegram:
    name: Notify Telegram
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - uses: actions/setup-node@v6
        with:
          node-version: 24

      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Send Releases
        run: |
          if [ "${{ inputs.nightly }}" = "true" ]; then
            deno run -A scripts/deno/telegram-notify.ts --nightly

          else
            deno run -A scripts/deno/telegram-notify.ts
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_API_ID: ${{ secrets.TELEGRAM_API_ID }}
          TELEGRAM_API_HASH: ${{ secrets.TELEGRAM_API_HASH }}
          FILE_SERVER_TOKEN: ${{ secrets.FILE_SERVER_TOKEN }}
          TELEGRAM_TO: '@keikolog'
          TELEGRAM_TO_NIGHTLY: '@ClashNyanpasu'
          WORKFLOW_RUN_ID: ${{ github.run_id }}
