name: '[Entire] Build Developer Version'

on:
  workflow_dispatch:
  schedule:
    - cron: '15 0 * * *' # 每天 08:15 UTC+8 自动构建

env:
  CARGO_INCREMENTAL: 0
  RUST_BACKTRACE: short

jobs:
  delete_current_releases:
    name: Delete Current Releases
    if: ${{ github.event_name == 'workflow_dispatch' || startsWith(github.repository, 'libnyanpasu') }}
    uses: ./.github/workflows/deps-delete-releases.yaml
    with:
      tag: 'pre-release'

  windows_amd64_build:
    name: Windows x86_64 Build
    uses: ./.github/workflows/deps-build-windows-nsis.yaml
    needs: [delete_current_releases]
    with:
      portable: true
      nightly: true
      fixed-webview: false
      arch: 'x86_64'
      tag: 'pre-release'
    secrets: inherit

  windows_aarch64_build:
    name: Windows aarch64 Build
    uses: ./.github/workflows/deps-build-windows-nsis.yaml
    needs: [delete_current_releases]
    with:
      portable: true
      nightly: true
      fixed-webview: false
      arch: 'aarch64'
      tag: 'pre-release'
    secrets: inherit

  windows_i686_build:
    name: Windows i686 Build
    uses: ./.github/workflows/deps-build-windows-nsis.yaml
    needs: [delete_current_releases]
    with:
      portable: true
      nightly: true
      fixed-webview: false
      arch: 'i686'
      tag: 'pre-release'
    secrets: inherit

  windows_amd64_build_fixed_webview:
    name: Windows x86_64 Build with Fixed WebView
    uses: ./.github/workflows/deps-build-windows-nsis.yaml
    needs: [delete_current_releases]
    with:
      portable: true
      nightly: true
      arch: 'x86_64'
      fixed-webview: true
      tag: 'pre-release'
    secrets: inherit

  windows_aarch64_build_fixed_webview:
    name: Windows aarch64 Build with Fixed WebView
    uses: ./.github/workflows/deps-build-windows-nsis.yaml
    needs: [delete_current_releases]
    with:
      portable: true
      nightly: true
      arch: 'aarch64'
      fixed-webview: true
      tag: 'pre-release'
    secrets: inherit

  windows_i686_build_fixed_webview:
    name: Windows i686 Build with Fixed WebView
    uses: ./.github/workflows/deps-build-windows-nsis.yaml
    needs: [delete_current_releases]
    with:
      portable: true
      nightly: true
      arch: 'i686'
      fixed-webview: true
      tag: 'pre-release'
    secrets: inherit

  linux_amd64_build:
    name: Linux amd64 Build
    uses: ./.github/workflows/deps-build-linux.yaml
    needs: [delete_current_releases]
    with:
      nightly: true
      tag: 'pre-release'
      arch: 'x86_64'
    secrets: inherit

  linux_i686_build:
    name: Linux i686 Build
    uses: ./.github/workflows/deps-build-linux.yaml
    needs: [delete_current_releases]
    with:
      nightly: true
      tag: 'pre-release'
      arch: 'i686'
    secrets: inherit

  linux_aarch64_build:
    name: Linux aarch64 Build
    uses: ./.github/workflows/deps-build-linux.yaml
    needs: [delete_current_releases]
    with:
      nightly: true
      tag: 'pre-release'
      arch: 'aarch64'
    secrets: inherit

  linux_armhf_build:
    name: Linux armhf Build
    uses: ./.github/workflows/deps-build-linux.yaml
    needs: [delete_current_releases]
    with:
      nightly: true
      tag: 'pre-release'
      arch: 'armhf'
    secrets: inherit

  linux_armel_build:
    name: Linux armel Build
    uses: ./.github/workflows/deps-build-linux.yaml
    needs: [delete_current_releases]
    with:
      nightly: true
      tag: 'pre-release'
      arch: 'armel'
    secrets: inherit

  macos_amd64_build:
    name: macOS amd64 Build
    uses: ./.github/workflows/deps-build-macos.yaml
    needs: [delete_current_releases]
    with:
      nightly: true
      aarch64: false
      tag: 'pre-release'
    secrets: inherit

  macos_aarch64_build:
    name: macOS aarch64 Build
    uses: ./.github/workflows/deps-build-macos.yaml
    needs: [delete_current_releases]
    with:
      nightly: true
      aarch64: true
      tag: 'pre-release'
    secrets: inherit

  update_tag:
    name: Update tag
    needs:
      [
        windows_amd64_build,
        windows_i686_build,
        windows_aarch64_build,
        windows_amd64_build_fixed_webview,
        windows_i686_build_fixed_webview,
        windows_aarch64_build_fixed_webview,
        linux_amd64_build,
        linux_i686_build,
        linux_aarch64_build,
        linux_armhf_build,
        linux_armel_build,
        macos_amd64_build,
        macos_aarch64_build,
      ]
    uses: ./.github/workflows/deps-update-tag.yaml
    with:
      tag: 'pre-release'

  updater:
    name: Create Updater
    needs: [update_tag]
    uses: ./.github/workflows/deps-create-updater.yaml
    with:
      nightly: true

  telegram:
    name: Send Release Message to Telegram
    if: startsWith(github.repository, 'libnyanpasu')
    needs: [update_tag]
    uses: ./.github/workflows/deps-message-telegram.yaml
    with:
      nightly: true
    secrets: inherit
